os:
  - linux
  - osx

language: node_js

node_js:
  - "node"
  - "lts/*"

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - "yarn global add bs-platform"
  - "yarn install"
  - "yarn link bs-platform"

test:
  - "yarn test"
