os:
  - linux
  - osx

language: node_js

node_js:
  - "node"
  - "lts/*"

cache: yarn

install:
  - "yarn global add bs-platform"
  - "yarn install"
  - "yarn link bs-platform"

test:
  - "yarn test"
